version: '3.8'

services:
  vinnare-app:
    container_name: vinnare-app
    image: vinnare:latest
    # build:
    #   context: .
    #   dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      DOTNET_RUNNING_IN_CONTAINER: "true"
    volumes:
      - ./logs:/etc/nginx/nginx.conf:ro
    networks:
      - vinnare

  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      DASHBOARD__TELEMETRYLIMITS__MAXLOGCOUNT: "500"
      DASHBOARD__TELEMETRYLIMITS__MAXTRACECOUNT: "500"
      DASHBOARD__TELEMETRYLIMITS__MAXMETRICSCOUNT: "500"
    networks:
      - vinnare

  nginx:
    container_name: vinnare-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    depends_on:
      - vinnare-app
      - aspire-dashboard
    networks:
      - vinnare

networks:
  vinnare:
    driver: bridge