name: cd

on:
  workflow_call:              
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      ec2_host:
        required: true        
      ec2_user:
        required: true
      ec2_ssh_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ec2_host }}
          username: ${{ secrets.ec2_user }}
          key: ${{ secrets.ec2_ssh_key }}
          script: |
            export AWS_REGION="${{ secrets.AWS_REGION }}"
            export AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"
            export ECR_REPOSITORY="${{ secrets.ECR_REPOSITORY }}"
            export IMAGE_TAG="${{ inputs.image_tag }}"

            echo "Pulling latest image..."
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
            docker stop vinnare || true
            docker rm vinnare || true
            docker run -d --name vinnare -p 8080:8080 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
