name: cd

on:
  workflow_call:              
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      ec2_host:
        required: true        
      ec2_user:
        required: true
      ec2_ssh_key:
        required: true
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      ECR_REPOSITORY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ec2_host }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            if [[ -z "${{ inputs.image_tag }}" ]]; then
              echo "ERROR: image_tag is empty! Exiting..."
              exit 1
            fi
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ inputs.image_tag }}
            echo "Pulled successfully"
      
      
            echo "Retagging image to 'vinnare:latest'"
            docker tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ inputs.image_tag }} vinnare:latest

            echo "Shutting down old containers (if any)..."
            docker-compose down || true

            echo "Starting new containers..."
            docker-compose up -d
