name: cd

on:
  workflow_call:
    inputs:
      ec2_host:
        required: true
        type: string
      ec2_user:
        required: true
        type: string
    secrets:
      ec2_ssh_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ inputs.ec2_host }}
          username: ${{ inputs.ec2_user }}
          key: ${{ secrets.ec2_ssh_key }}
          script: |
            echo "Pulling latest image..."
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
            docker stop vinnare || true
            docker rm vinnare || true
            docker run -d --name vinnare -p 8080:8080 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
