name: ci

on:  
  push:
    branches: ["actions"]
  pull_request:
    branches: ["main"]


jobs:
  build-test-push:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.extract_commit.outputs.commit_hash }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract commit hash
        id: extract_commit
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t vinnare:${{ steps.extract_commit.outputs.commit_hash }} . -f ./Api/Dockerfile

      - name: Run tests (placeholder)
        run: |
          echo "Running tests..."
          # TODO: Replace with actual test command
          # docker run --rm vinnare:${{ steps.extract_commit.outputs.commit_hash }} dotnet test
          - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Log in to Amazon ECR
        if: success()  # Only runs if previous steps pass
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
            AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Tag and push Docker image to AWS ECR
        run: |
          docker tag vinnare:${{ needs.build-and-test.outputs.commit_hash }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ needs.build-and-test.outputs.commit_hash }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ needs.build-and-test.outputs.commit_hash }}

      - name: Notify deployment pipeline
        run: echo "IMAGE_TAG=${{ needs.build-and-test.outputs.commit_hash }}" >> $GITHUB_ENV

  
  
  deploy:
    needs: build-test-push
    uses: ./.github/workflows/cd.yml    
    with:
      image_tag: ${{ needs.build-and-test.outputs.commit_hash }}  # Pass commit hash as image tag
    secrets:
      ec2_host: ${{ secrets.EC2_HOST }}
      ec2_user: ${{ secrets.EC2_USER }}
      ec2_ssh_key: ${{ secrets.EC2_SSH_KEY }}
